{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}
module PrintCpp where

-- pretty-printer generated by the BNF converter

import AbsCpp
import Data.Char


-- the top-level printing method
printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : ts@(p:_) | closingOrPunctuation p -> showString t . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else ' ':s)
  closingOrPunctuation [c] = c `elem` ")],;."
  closingOrPunctuation _   = False

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- the printer class does the job
class Print a where
  prt :: Int -> a -> Doc
  prtList :: Int -> [a] -> Doc
  prtList i = concatD . map (prt i)

instance Print a => Print [a] where
  prt = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList _ s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j<i then parenth else id


instance Print Integer where
  prt _ x = doc (shows x)


instance Print Double where
  prt _ x = doc (shows x)



instance Print CIdent where
  prt _ (CIdent i) = doc (showString ( i))
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString ","), prt 0 xs])


instance Print Program where
  prt i e = case e of
    PDefs defs -> prPrec i 0 (concatD [prt 0 defs])

instance Print Def where
  prt i e = case e of
    DFun type_ cident args fbod -> prPrec i 0 (concatD [prt 0 type_, prt 0 cident, doc (showString "("), prt 0 args, doc (showString ")"), prt 0 fbod])
    DType typedef -> prPrec i 0 (concatD [prt 0 typedef, doc (showString ";")])
    DDcl decl -> prPrec i 0 (concatD [prt 0 decl, doc (showString ";")])
    DUs qconst -> prPrec i 0 (concatD [doc (showString "using"), prt 0 qconst, doc (showString ";")])
  prtList _ [] = (concatD [])
  prtList _ (x:xs) = (concatD [prt 0 x, prt 0 xs])
instance Print Arg where
  prt i e = case e of
    ArgVar argdecl -> prPrec i 0 (concatD [prt 0 argdecl])
    ArgCons argdecl -> prPrec i 0 (concatD [doc (showString "const"), prt 0 argdecl])
  prtList _ [] = (concatD [])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString ","), prt 0 xs])
instance Print ArgDecl where
  prt i e = case e of
    ADeclType type_ -> prPrec i 0 (concatD [prt 0 type_])
    ADeclVar type_ cident -> prPrec i 0 (concatD [prt 0 type_, prt 0 cident])
    ADeclInit type_ cident exp -> prPrec i 0 (concatD [prt 0 type_, prt 0 cident, doc (showString "="), prt 0 exp])

instance Print FBod where
  prt i e = case e of
    FBodBlck stms -> prPrec i 0 (concatD [doc (showString "{"), prt 0 stms, doc (showString "}")])
    FBodNil -> prPrec i 0 (concatD [doc (showString ";")])

instance Print Stm where
  prt i e = case e of
    SExp exp -> prPrec i 0 (concatD [prt 0 exp, doc (showString ";")])
    SDecl decl -> prPrec i 0 (concatD [prt 0 decl, doc (showString ";")])
    SRet exp -> prPrec i 0 (concatD [doc (showString "return"), prt 0 exp, doc (showString ";")])
    SWhile exp stm -> prPrec i 0 (concatD [doc (showString "while"), doc (showString "("), prt 0 exp, doc (showString ")"), prt 0 stm])
    SDoWhile stm exp -> prPrec i 0 (concatD [doc (showString "do"), prt 0 stm, doc (showString "while"), doc (showString "("), prt 0 exp, doc (showString ")"), doc (showString ";")])
    SFor decl exp1 exp2 stm -> prPrec i 0 (concatD [doc (showString "for"), doc (showString "("), prt 0 decl, doc (showString ";"), prt 0 exp1, doc (showString ";"), prt 0 exp2, doc (showString ")"), prt 0 stm])
    SIf exp stm -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 exp, doc (showString ")"), prt 0 stm])
    SIfEl exp stm1 stm2 -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 exp, doc (showString ")"), prt 0 stm1, doc (showString "else"), prt 0 stm2])
    SBlock stms -> prPrec i 0 (concatD [doc (showString "{"), prt 0 stms, doc (showString "}")])
    STyp typedef -> prPrec i 0 (concatD [prt 0 typedef, doc (showString ";")])
  prtList _ [] = (concatD [])
  prtList _ (x:xs) = (concatD [prt 0 x, prt 0 xs])
instance Print Decl where
  prt i e = case e of
    DclVar declinit -> prPrec i 0 (concatD [prt 0 declinit])
    DclCons declinit -> prPrec i 0 (concatD [doc (showString "const"), prt 0 declinit])

instance Print DeclInit where
  prt i e = case e of
    DclNoInit type_ cident -> prPrec i 0 (concatD [prt 0 type_, prt 0 cident])
    Dcls type_ cident cidents -> prPrec i 0 (concatD [prt 0 type_, prt 0 cident, doc (showString ","), prt 0 cidents])
    DclInit type_ cident exp -> prPrec i 0 (concatD [prt 0 type_, prt 0 cident, doc (showString "="), prt 0 exp])

instance Print TypeDef where
  prt i e = case e of
    TDef type_ cident -> prPrec i 0 (concatD [doc (showString "typedef"), prt 0 type_, prt 0 cident])

instance Print Type where
  prt i e = case e of
    TBool -> prPrec i 0 (concatD [doc (showString "bool")])
    TInt -> prPrec i 0 (concatD [doc (showString "int")])
    TChar -> prPrec i 0 (concatD [doc (showString "char")])
    TDouble -> prPrec i 0 (concatD [doc (showString "double")])
    TVoid -> prPrec i 0 (concatD [doc (showString "void")])
    TConst qconst -> prPrec i 0 (concatD [prt 0 qconst])
    TRef type_ -> prPrec i 0 (concatD [prt 0 type_, doc (showString "&")])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString ","), prt 0 xs])
instance Print Exp where
  prt i e = case e of
    EThr exp -> prPrec i 0 (concatD [doc (showString "throw"), prt 1 exp])
    ECond exp1 exp2 exp3 -> prPrec i 1 (concatD [prt 2 exp1, doc (showString "?"), prt 1 exp2, doc (showString ":"), prt 1 exp3])
    EAss exp1 exp2 -> prPrec i 2 (concatD [prt 3 exp1, doc (showString "="), prt 2 exp2])
    EPEq exp1 exp2 -> prPrec i 2 (concatD [prt 3 exp1, doc (showString "+="), prt 2 exp2])
    EMEq exp1 exp2 -> prPrec i 2 (concatD [prt 3 exp1, doc (showString "-="), prt 2 exp2])
    EOr exp1 exp2 -> prPrec i 3 (concatD [prt 3 exp1, doc (showString "||"), prt 4 exp2])
    EAnd exp1 exp2 -> prPrec i 4 (concatD [prt 4 exp1, doc (showString "&&"), prt 5 exp2])
    EEq exp1 exp2 -> prPrec i 8 (concatD [prt 9 exp1, doc (showString "=="), prt 9 exp2])
    ENEq exp1 exp2 -> prPrec i 8 (concatD [prt 9 exp1, doc (showString "!="), prt 9 exp2])
    ELt exp1 exp2 -> prPrec i 9 (concatD [prt 10 exp1, doc (showString "<"), prt 10 exp2])
    EGt exp1 exp2 -> prPrec i 9 (concatD [prt 10 exp1, doc (showString ">"), prt 10 exp2])
    ELtEq exp1 exp2 -> prPrec i 9 (concatD [prt 10 exp1, doc (showString "<="), prt 10 exp2])
    EGtWq exp1 exp2 -> prPrec i 9 (concatD [prt 10 exp1, doc (showString ">="), prt 10 exp2])
    ELShift exp1 exp2 -> prPrec i 10 (concatD [prt 10 exp1, doc (showString "<<"), prt 11 exp2])
    ERShift exp1 exp2 -> prPrec i 10 (concatD [prt 10 exp1, doc (showString ">>"), prt 11 exp2])
    EAdd exp1 exp2 -> prPrec i 11 (concatD [prt 11 exp1, doc (showString "+"), prt 12 exp2])
    ESub exp1 exp2 -> prPrec i 11 (concatD [prt 11 exp1, doc (showString "-"), prt 12 exp2])
    EMul exp1 exp2 -> prPrec i 12 (concatD [prt 12 exp1, doc (showString "*"), prt 13 exp2])
    EDiv exp1 exp2 -> prPrec i 12 (concatD [prt 12 exp1, doc (showString "/"), prt 13 exp2])
    EMod exp1 exp2 -> prPrec i 12 (concatD [prt 12 exp1, doc (showString "%"), prt 13 exp2])
    EIncr exp -> prPrec i 13 (concatD [doc (showString "++"), prt 14 exp])
    EDecr exp -> prPrec i 13 (concatD [doc (showString "--"), prt 14 exp])
    ENot exp -> prPrec i 13 (concatD [doc (showString "!"), prt 13 exp])
    EPtr exp -> prPrec i 13 (concatD [doc (showString "*"), prt 13 exp])
    EPIncr exp -> prPrec i 14 (concatD [prt 15 exp, doc (showString "++")])
    EPDecr exp -> prPrec i 14 (concatD [prt 15 exp, doc (showString "--")])
    EDot exp1 exp2 -> prPrec i 14 (concatD [prt 14 exp1, doc (showString "."), prt 15 exp2])
    EArr exp1 exp2 -> prPrec i 14 (concatD [prt 14 exp1, doc (showString "->"), prt 15 exp2])
    EFCall exp exps -> prPrec i 15 (concatD [prt 16 exp, doc (showString "("), prt 0 exps, doc (showString ")")])
    EInd exp1 exp2 -> prPrec i 15 (concatD [prt 15 exp1, doc (showString "["), prt 0 exp2, doc (showString "]")])
    EQConst qconst -> prPrec i 16 (concatD [prt 0 qconst])
    EInt n -> prPrec i 16 (concatD [prt 0 n])
    EChar c -> prPrec i 16 (concatD [prt 0 c])
    EDoub d -> prPrec i 16 (concatD [prt 0 d])
    EStr strs -> prPrec i 16 (concatD [prt 0 strs])
  prtList _ [] = (concatD [])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString ","), prt 0 xs])
instance Print QConst where
  prt i e = case e of
    QConstMain qconstels -> prPrec i 0 (concatD [prt 0 qconstels])

instance Print QConstEl where
  prt i e = case e of
    QConstCIdent cident -> prPrec i 0 (concatD [prt 0 cident])
    QConstTp cident types -> prPrec i 0 (concatD [prt 0 cident, doc (showString "<"), prt 0 types, doc (showString ">")])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString "::"), prt 0 xs])

